#!/usr/bin/env node
/**
 * Media audit — the generator behind the coverage matrix in docs/11 §2 (concerns) and
 * docs/13 §3 (treatments), and behind config/*-media.json.
 *
 *   pnpm audit:concern-media              # print the coverage matrix
 *   pnpm audit:treatment-media --write    # rewrite the doc's matrix in place
 *   pnpm audit:treatment-media --manifest # rewrite the manifest
 *
 * This file is the machinery only: read a source folder, measure every image, hand the
 * files to a page-type config for classification and key assignment, then emit. The facts
 * — which folders, which slugs, which files were classified by opening them — live in
 * scripts/media/<type>.mjs beside it. One implementation, two page types: two near-identical
 * audit scripts would drift, and the drift ships as a page that 404s its own imagery.
 *
 * Source folders are the designer's local export (see .env.example), never the repo:
 * 80 MB of binaries is permanent git weight we chose not to carry (ADR-0001 §4).
 *
 * ponytail: dimensions come from macOS `sips`. This is local designer/dev tooling that
 * already requires the source folder on disk; port to a pure-JS header reader only if it
 * ever needs to run in CI.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { loadMediaConfig } from "./media/load.mjs";

const IMAGE = /\.(jpe?g|png|gif|webp|avif)$/i;

const type = process.argv[2];
const { cfg, source: SOURCE } = await loadMediaConfig(type);

/** One `sips` call for the whole set; it prints a block per file in argument order. */
function dimensions(paths) {
  const out = execFileSync("sips", ["-g", "pixelWidth", "-g", "pixelHeight", ...paths], {
    encoding: "utf8",
    maxBuffer: 1 << 24,
  });
  const dims = [];
  let width;
  for (const line of out.split("\n")) {
    const w = line.match(/pixelWidth:\s*(\d+)/);
    const h = line.match(/pixelHeight:\s*(\d+)/);
    if (w) width = Number(w[1]);
    if (h) dims.push({ width, height: Number(h[1]) });
  }
  if (dims.length !== paths.length) throw new Error(`sips returned ${dims.length} of ${paths.length}`);
  return dims;
}

function scan() {
  const files = [];
  for (const folder of cfg.folders) {
    // Recursive: the treatment source keeps its logo and collab marks in subfolders.
    for (const path of readdirSync(join(SOURCE, folder), { recursive: true }).sort()) {
      // desktop.ini, .DS_Store and any other stowaway: `sips` exits non-zero on them.
      if (!IMAGE.test(path)) continue;
      // `name` is the basename and `path` is folder-relative. Every classifier reads the
      // filename, and anchored patterns like /^pbanner/ would stop matching the moment a
      // file moved into a subfolder — so the split is made here, once, not per config.
      files.push({ folder, path, name: basename(path), source: `${folder}/${path}` });
    }
  }
  const dims = dimensions(files.map((f) => join(SOURCE, f.source)));
  files.forEach((f, i) => {
    f.width = dims[i].width;
    f.height = dims[i].height;
    cfg.classify(f);
  });
  cfg.assignKeys(files);
  return files;
}

const files = scan();
const { table, summary } = cfg.matrix(files);

if (process.argv.includes("--manifest")) {
  const manifest = {
    "//": `Generated by scripts/media-audit.mjs ${type} --manifest. Source binaries are not committed (ADR-0001 §4); this file is both the provenance record and the upload plan for scripts/sync-media.mjs.`,
    bucketPrefix: cfg.bucketPrefix,
    publicBase: cfg.publicBase,
    assets: files.map((f) => ({
      source: f.source,
      key: f.key,
      [cfg.groupField]: f.group,
      family: f.family,
      width: f.width,
      height: f.height,
      // Present means "mapped, but do not upload" — the reason is the whole point.
      ...(f.hold ? { hold: f.hold } : {}),
    })),
  };
  writeFileSync(cfg.manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  const held = files.filter((f) => f.hold).length;
  console.log(`${cfg.manifestPath}: ${files.length} assets, ${held} held back`);
} else if (process.argv.includes("--write")) {
  const doc = readFileSync(cfg.docPath, "utf8");
  const next = doc.replace(cfg.docAnchor, `$1${table}\n\n`);
  if (next === doc) throw new Error(`${cfg.docPath}: matrix not found — has the heading changed?`);
  writeFileSync(cfg.docPath, next);
  console.log(`${cfg.docPath} matrix rewritten (${files.length} files)`);
} else {
  console.log(table);
  console.log(`\n${summary}`);
}
