#!/usr/bin/env node
/**
 * Uploads concern or treatment media to R2 from the local source folder, renaming on the
 * way up.
 *
 *   pnpm sync:treatment-media --dry-run   # print every planned upload, write nothing
 *   pnpm sync:treatment-media             # stage under the CDN keys and sync
 *
 * The plan is config/<type>-media.json (generated by media-audit.mjs --manifest); the only
 * page-type facts this script needs — the manifest path and the source env var — come from
 * scripts/media/<type>.mjs, the same config the audit reads. The divergence from the blog's
 * staged-in-repo model is recorded in ADR-0001 §4: the source binaries never enter git, so
 * the manifest is the only thing that has to.
 *
 * Credentials come from the environment, never the repo. Locally that means .env.local
 * (loaded by the pnpm script); in CI it would be the same GitHub secrets the blog sync uses.
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { loadMediaConfig } from "./media/load.mjs";

const type = process.argv[2];
const { cfg, source: SOURCE } = await loadMediaConfig(type);
const manifest = JSON.parse(readFileSync(cfg.manifestPath, "utf8"));
const dryRun = process.argv.includes("--dry-run");
const prefix = manifest.bucketPrefix;

// A `hold` on an asset is a decision recorded in the manifest — an unconfirmed-ownership
// watermark (ADR-0001 §5), a partner brand mark, or a file no page reads. Held never uploads.
const held = manifest.assets.filter((a) => a.hold);
const assets = manifest.assets.filter((a) => !a.hold);
for (const a of held) console.log(`held: ${a.source} — ${a.hold}`);

let bytes = 0;
for (const a of assets) {
  const path = join(SOURCE, a.source);
  bytes += statSync(path).size; // Fails loudly if the source folder is stale.
  if (dryRun) console.log(`${a.source}\n  → s3://<bucket>/${a.key}`);
}
console.log(
  `\n${assets.length} objects · ${(bytes / 1e6).toFixed(1)} MB · ${held.length} held back`,
);

if (dryRun) {
  console.log("dry run — nothing uploaded");
  process.exit(0);
}

const required = ["R2_ACCOUNT_ID", "R2_BUCKET_NAME", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"];
const missing = required.filter((k) => !process.env[k]);
if (missing.length) {
  console.error(`missing ${missing.join(", ")} — set them in .env.local (see .env.example)`);
  process.exit(1);
}

// Stage a tree named by CDN key so one `aws s3 sync` does the whole upload, with the
// same --size-only semantics the blog media workflow relies on.
const stage = mkdtempSync(join(tmpdir(), `${type}-media-`));
try {
  for (const a of assets) {
    if (!a.key.startsWith(prefix)) throw new Error(`${a.key} is outside ${prefix}`);
    const dest = join(stage, a.key.slice(prefix.length));
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(join(SOURCE, a.source), dest);
  }

  const env = {
    ...process.env,
    AWS_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    AWS_DEFAULT_REGION: "auto",
    // R2 rejects the CRC32 trailer the AWS CLI v2 sends by default.
    AWS_REQUEST_CHECKSUM_CALCULATION: "when_required",
    AWS_RESPONSE_CHECKSUM_VALIDATION: "when_required",
  };
  const endpoint = `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`;
  const target = `s3://${process.env.R2_BUCKET_NAME}/${prefix.replace(/\/$/, "")}`;

  // No --delete: dropping a file from the manifest must not 404 a URL Google already has.
  execFileSync(
    "aws",
    ["s3", "sync", stage, target, "--endpoint-url", endpoint, "--size-only", "--no-progress"],
    { env, stdio: "inherit" },
  );

  // Existence check: the bucket must now hold at least what the manifest planned.
  const listed = execFileSync(
    "aws",
    ["s3", "ls", `${target}/`, "--recursive", "--endpoint-url", endpoint],
    { env, encoding: "utf8", maxBuffer: 1 << 24 },
  )
    .split("\n")
    .filter(Boolean).length;
  console.log(`${listed} objects under ${target}/ (manifest plans ${assets.length})`);
  if (listed < assets.length) process.exit(1);
} finally {
  rmSync(stage, { recursive: true, force: true });
}
